---
title: "R Notebook"
author: "Yi-Ming Gan"
date: "`r Sys.Date()`"
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "html") })
output:
  html_document:
    df_print: paged
    
---

Transform SO isotopes masterfile data into occurrence core and measurement or fact extension.

```{r}
# read dataset from url
data <- read.csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vSfAaU0p3QOsyugCL72TJuHq-pH1XyWGs1A8qIFDp1ndqqehxP4a9Lnc6QGxf1g-qU1abdNHfCwUG7p/pub?gid=193721447&single=true&output=tsv", header = TRUE, sep = "\t", check.names = FALSE)

head(data)
names(data)
```

```{r}
# occurrence data frame spans from column 1-37, all columns beyond that belongs to measurement or fact extension
occ_df <- data[, 1:37]
head(occ_df)
```

```{r echo=FALSE, message=FALSE}
library(tidyverse)

create_var_mof <- function(data = data, core_id = "occurrenceID", measurement_col, measurement_type, measurement_unit, measurement_remarks = "") {
  # create a measurement or fact table of a single measurement type from the data
  # subset the occurrence data
  mof <- data %>% 
    # remove rows of measurement which are NULL
    filter(!is.na(!!as.symbol(measurement_col))) %>%  # !!as.symbol is required as column name is passed as string
    select(!!as.symbol(core_id), !!as.symbol(measurement_col))
  
  # create mof table (long table)
  mof_df <- data.frame(
    occurrenceID = mof[, core_id],
    measurementType = replicate(nrow(mof), measurement_type),
    measurementValue = mof[, measurement_col],
    measurmentUnit = measurement_unit,
    measurementRemarks = measurement_remarks
  )
  return(mof_df)
}
```


Arm length, disc radius and arm to disc ratio

```{r}
armLength <- create_var_mof(data = data, core_id = "occurrenceID", measurement_col = "Arm length_R_(cm)", measurement_type = "Arm length_R_(cm)", measurement_unit = "cm", measurement_remarks = "")
discRadius <- create_var_mof(data = data, core_id = "occurrenceID", measurement_col = "Disc radius_r_(cm)", measurement_type = "Disc radius_r_(cm)", measurement_unit = "cm", measurement_remarks = "")
rRRatio <- create_var_mof(data = data, core_id = "occurrenceID", measurement_col = "R_r_ratio", measurement_type = "R_r_ratio", measurement_unit = "", measurement_remarks = "")
```


delta C13, N15, S34 of tegument and podia

```{r}
# d13C

d13C_tegument <- create_var_mof(data = data, core_id = "occurrenceID", measurement_col = "d13C_tegument", measurement_type = "d13C", measurement_unit = "", measurement_remarks = "tegument")
d13C_podia<- create_var_mof(data = data, core_id = "occurrenceID", measurement_col = "d13C_podia", measurement_type = "d13C", measurement_unit = "", measurement_remarks = "podia")

# d15N

d15N_tegument <- create_var_mof(data = data, core_id = "occurrenceID", measurement_col = "d15N_tegument", measurement_type = "d15N", measurement_unit = "", measurement_remarks = "tegument")
d15N_podia <- create_var_mof(data = data, core_id = "occurrenceID", measurement_col = "d15N_podia", measurement_type = "d15N", measurement_unit = "", measurement_remarks = "podia")

# d34S

d34S_tegument <- create_var_mof(data = data, core_id = "occurrenceID", measurement_col = "d34S_tegument", measurement_type = "d34S", measurement_unit = "", measurement_remarks = "tegument")
d34S_podia <- create_var_mof(data = data, core_id = "occurrenceID", measurement_col = "d34S_podia", measurement_type = "d34S", measurement_unit = "", measurement_remarks = "podia")

```

%C, %N, %S of tegument and podia

```{r}
# %C

percentage_C_tegument <- create_var_mof(data = data, core_id = "occurrenceID", measurement_col = "%C_tegument", measurement_type = "%C", measurement_unit = "", measurement_remarks = "tegument")
percentage_C_podia <- create_var_mof(data = data, core_id = "occurrenceID", measurement_col = "%C_podia", measurement_type = "%C", measurement_unit = "", measurement_remarks = "podia")

# %N 

percentage_N_tegument <- create_var_mof(data = data, core_id = "occurrenceID", measurement_col = "%N_tegument", measurement_type = "%N", measurement_unit = "", measurement_remarks = "tegument")
percentage_N_podia <- create_var_mof(data = data, core_id = "occurrenceID", measurement_col = "%N_podia", measurement_type = "%N", measurement_unit = "", measurement_remarks = "podia")


# %S

percentage_S_tegument <- create_var_mof(data = data, core_id = "occurrenceID", measurement_col = "%S_tegument", measurement_type = "%S", measurement_unit = "", measurement_remarks = "tegument")
percentage_S_podia <- create_var_mof(data = data, core_id = "occurrenceID", measurement_col = "%S_podia", measurement_type = "%S", measurement_unit = "", measurement_remarks = "podia")
```

C/N ratio of tegument and podia

```{r}
ratio_CN_tegument <- create_var_mof(data = data, core_id = "occurrenceID", measurement_col = "C/N_tegument", measurement_type = "Ratio_C/N", measurement_unit = "", measurement_remarks = "tegument")
ratio_CN_podia <- create_var_mof(data = data, core_id = "occurrenceID", measurement_col = "C_N_podia", measurement_type = "Ratio_C/N", measurement_unit = "", measurement_remarks = "podia")
```


# create measurement or fact data frame

```{r}
mof_df <- rbind(
  armLength,
  discRadius,
  rRRatio,
  d13C_tegument,
  d13C_podia,
  d15N_tegument,
  d15N_podia,
  d34S_tegument,
  d34S_podia,
  percentage_C_tegument,
  percentage_C_podia,
  percentage_N_tegument,
  percentage_N_podia,
  percentage_S_tegument,
  percentage_S_podia,
  ratio_CN_tegument,
  ratio_CN_podia
)

dim(mof_df) 

```

Write data frames to files.

```{r message=FALSE}
library(here)
library(readr)
outfile_dir <- here("data/processed")
occ_file <- file.path(outfile_dir, "occurrence.txt")
mof_file <- file.path(outfile_dir, "measurementOrFact.txt")

write_tsv(occ_df, file = occ_file, na = "")
write_tsv(mof_df, file = mof_file, na = "")
```
